### ISSUE TITLE
Update docs README

### ISSUE THREAD

**Issue by will-moore** [ome/omero-cli-zarr#26]
The README says you can use `--output` but trying seems to suggest not.
Also need to rename 'masks' to 'labels' in the README (and elsewhere?)

```
$ omero zarr export Image:139615 --output /Users/wmoore/Desktop/ZARR/data/
/Users/wmoore/opt/miniconda3/envs/omero zarr export: error: unrecognized arguments: --output /Users/wmoore/Desktop/ZARR/data/

```

**Comment by joshmoore** [comment]
Thanks, @will-moore. I'll pick these up in https://github.com/ome/omero-cli-zarr/pull/25

**Comment by joshmoore** [comment]
Try: ``omero zarr --output ... ` then "export" or "masks.

As for "masks", I was trying to get across that  we take omero.model.Masks from the server and turn them in Labels. Might need to make that explicit.

**Comment by will-moore** [comment]
Yep that worked:

```
$ omero zarr --output testoutput export Image:139615 
Using session for user-3@10.0.48.9:4064. Idle timeout: 10 min. Current group: read-only-1
loading plane c:0, t:0, z:0
loading plane c:1, t:0, z:0
loading plane c:2, t:0, z:0
Created testoutput/139615.zarr

```
